### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by sinoon** [liangzr/alfred-tools#2]
I think is very awesome and helpful.

And I wandering how to write Alfred workflow by is tool in whole way？

**Comment by liangzr** [comment]
Thanks for attention : )

Because the flow control of Alfred Workflow is managed by its configuration files, there is no way to write the entire workflow completely in code in an official way, but maybe you can parse the configuration file and write a DSL for it to describe the relationship of components(this will be an interesting exploration).

This project was inspired by [deanishe/alfred-workflow](https://github.com/deanishe/alfred-workflow) written in python, and its purpose is to help people create workflow more easily
